In [4]:
import numpy as np
ar1=np.arange(13)
ar1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [5]:
reshaped=ar1.reshape(13,1)
reshaped

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [6]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [9]:
np.identity(5,dtype=complex)

array([[1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j]])

In [8]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [10]:
len(ar1)

13

In [16]:
ar2=np.arange(25).reshape(5,5)

In [17]:
ar2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [18]:
ar2.shape

(5, 5)

In [25]:
ar2[1:3,1:3]

array([[ 6,  7],
       [11, 12]])

In [26]:
ar2[-1:-3]

array([], shape=(0, 5), dtype=int32)

In [27]:
ar2[-4:-2,-4:-2]

array([[ 6,  7],
       [11, 12]])

In [29]:
ar3=np.arange(50).reshape(5,10)
ar3

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [30]:
np.sum(ar3,axis=0)#coloumn

array([100, 105, 110, 115, 120, 125, 130, 135, 140, 145])

In [31]:
np.sum(ar3,axis=1)#row

array([ 45, 145, 245, 345, 445])

In [32]:
np.sum(ar3)

1225

In [33]:
#mean -->average
#median -->center value
#mode --> max num of repeated element
#variance --> median/total num of elements
#std--> square root of variance

In [45]:
#linspace()
np.linspace(1,100,5)

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

In [51]:
np.linspace(12,30,12,retstep=True)

(array([12.        , 13.63636364, 15.27272727, 16.90909091, 18.54545455,
        20.18181818, 21.81818182, 23.45454545, 25.09090909, 26.72727273,
        28.36363636, 30.        ]),
 1.6363636363636365)

In [65]:
np.random.randint(1,70,3)

array([39,  1, 57])

In [67]:
np.random.rand(4,3)

array([[0.09876847, 0.67805797, 0.79148571],
       [0.70374534, 0.96163198, 0.62092589],
       [0.6245603 , 0.31480647, 0.65427229],
       [0.87723386, 0.54329635, 0.40885276]])

In [68]:
ar3.min()

0

In [69]:
ar3.max()

49

In [73]:
l1=[56,63,49,83,5,6]
np1=np.array(l1)
print(np1.argmin())
print(np1.argmax())


4
3


In [75]:
np.sin(np1)/np.cos(np1)

array([-0.61127369,  0.16974975, -3.17290855,  3.88059631, -3.38051501,
       -0.29100619])

In [88]:
np2=np.array([1,2,3,])
np3=np.array([4,5,6])
r=(np2[0]*np3[0])+(np2[1]*np3[1])+(np2[2]*np3[2])
r

32

In [13]:
#pandas
#pandas is built on numpy,numpy is required for operating pandas
import pandas as pd

In [12]:
import numpy as np
labels=['a','b','c']
my_data=[10,20,30]
arr=np.array(my_data)
d={'a':100,'b':200,'c':300}
pd.Series(my_data)

0    10
1    20
2    30
dtype: int64

In [15]:
ser1=pd.Series([1,2,3,4,5],['australia','india','newzealand','usa','uk'])

In [16]:
ser1

australia     1
india         2
newzealand    3
usa           4
uk            5
dtype: int64

In [18]:
ser1['india']

2

In [20]:
ser1[1:3]

india         2
newzealand    3
dtype: int64

In [33]:
df=pd.DataFrame(np.random.randn(5,4),['a','b','c','d','e'])

In [34]:
df

0         1         2         3
a  1.245150 -0.360055 -1.846772  1.234116
b -0.451879 -0.855866 -1.840108 -0.750726
c  0.874609 -0.190015 -0.558671 -2.143274
d  1.231099  1.537317  1.929183 -0.652509
e  0.285039  0.746006  0.607972 -1.036253

In [25]:
d={'col':[1,2],'co12':[3,4],'co13':[5,6]}
d

{'col': [1, 2], 'co12': [3, 4], 'co13': [5, 6]}

In [26]:
df=pd.DataFrame(data=d)
df

col  co12  co13
0    1     3     5
1    2     4     6

In [27]:
df=pd.DataFrame(d,['row1','row2'])

In [32]:
df

col  co12  co13
row1    1     3     5
row2    2     4     6

In [35]:
df

0         1         2         3
a  1.245150 -0.360055 -1.846772  1.234116
b -0.451879 -0.855866 -1.840108 -0.750726
c  0.874609 -0.190015 -0.558671 -2.143274
d  1.231099  1.537317  1.929183 -0.652509
e  0.285039  0.746006  0.607972 -1.036253

In [36]:
type(df)


pandas.core.frame.DataFrame

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, a to e
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       5 non-null      float64
 1   1       5 non-null      float64
 2   2       5 non-null      float64
 3   3       5 non-null      float64
dtypes: float64(4)
memory usage: 200.0+ bytes


In [40]:
df.values

array([[ 1.24515016, -0.36005468, -1.84677227,  1.23411595],
       [-0.45187891, -0.85586618, -1.84010791, -0.7507263 ],
       [ 0.87460942, -0.19001504, -0.55867085, -2.14327367],
       [ 1.23109945,  1.53731654,  1.92918294, -0.65250873],
       [ 0.28503927,  0.74600576,  0.607972  , -1.0362528 ]])

In [41]:
df.axes


[Index(['a', 'b', 'c', 'd', 'e'], dtype='object'),
 RangeIndex(start=0, stop=4, step=1)]

In [42]:
df.size

20

In [49]:
df[0]

a    1.245150
b   -0.451879
c    0.874609
d    1.231099
e    0.285039
Name: 0, dtype: float64

In [51]:
df["new"]=df[0]

In [52]:
df

0         1         2         3       new
a  1.245150 -0.360055 -1.846772  1.234116  1.245150
b -0.451879 -0.855866 -1.840108 -0.750726 -0.451879
c  0.874609 -0.190015 -0.558671 -2.143274  0.874609
d  1.231099  1.537317  1.929183 -0.652509  1.231099
e  0.285039  0.746006  0.607972 -1.036253  0.285039

In [53]:
df.drop('new',axis=1,inplace=True)

In [54]:
df

0         1         2         3
a  1.245150 -0.360055 -1.846772  1.234116
b -0.451879 -0.855866 -1.840108 -0.750726
c  0.874609 -0.190015 -0.558671 -2.143274
d  1.231099  1.537317  1.929183 -0.652509
e  0.285039  0.746006  0.607972 -1.036253