In [1]:
import numpy as np
l1=[10,20,30,40,50]
arr=np.array(l1)
print(arr)

[10 20 30 40 50]


In [3]:
type(list(arr))

list

In [4]:
type(arr)

numpy.ndarray

In [5]:
arr.tolist()

[10, 20, 30, 40, 50]

In [12]:
#arr*2
#arr+4
#arr/3

array([ 3.33333333,  6.66666667, 10.        , 13.33333333, 16.66666667])

In [14]:
ar2=[1,2,3,45,9,89.2]
np_ar=np.array(ar2)
np_ar

array([ 1. ,  2. ,  3. , 45. ,  9. , 89.2])

In [17]:
new_ar=np.append(np_ar,78,789)
new_ar

array([ 1. ,  2. ,  3. , 45. ,  9. , 89.2, 78. ])

In [20]:
new_ar=np.append(np_ar,[56,90,89])
print(new_ar)

[ 1.   2.   3.  45.   9.  89.2 56.  90.  89. ]


In [21]:
new_ar=np.insert(np_ar,2,123)
print(new_ar)

[  1.    2.  123.    3.   45.    9.   89.2]


In [22]:
new_ar=np.insert(np_ar,2,(456,852,185))
print(new_ar)

[  1.    2.  456.  852.  185.    3.   45.    9.   89.2]


In [23]:
np_ar

array([ 1. ,  2. ,  3. , 45. ,  9. , 89.2])

In [25]:
nr=np.delete(np_ar,np.where(np_ar==2.0))
nr

array([ 1. ,  3. , 45. ,  9. , 89.2])

In [27]:
nr=np.setdiff1d(np_ar,[1.0,2.0,9.0])
nr

array([ 3. , 45. , 89.2])

In [32]:
nr=np.delete(np_ar,[3,4])
nr

array([ 1. ,  2. ,  3. , 89.2])

In [35]:
l1=[1,45,23,90,78,12,94,26,15,8,7]
new_ar=np.array(l1)
print(new_ar)

[ 1 45 23 90 78 12 94 26 15  8  7]


In [36]:
new_ar<30

array([ True, False,  True, False, False,  True, False,  True,  True,
        True,  True])

In [37]:
new_ar[new_ar<30]

array([ 1, 23, 12, 26, 15,  8,  7])

In [38]:
new_ar

array([ 1, 45, 23, 90, 78, 12, 94, 26, 15,  8,  7])

In [39]:
(new_ar<20) & (new_ar>50)

array([False, False, False, False, False, False, False, False, False,
       False, False])

In [44]:
new_ar[(new_ar>20) & (new_ar<50)]

array([45, 23, 26])

In [47]:
new_ar[new_ar==23]=156
new_ar

array([  1,  45, 156,  90,  78,  12,  94,  26,  15,   8,   7])

In [50]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [51]:
np.zeros([3,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [52]:
np.ones(4)

array([1., 1., 1., 1.])

In [56]:
np.ones([3,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [57]:
np.ones([3,4,5])

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [60]:
type(new_ar)
new_ar.dtype

dtype('int64')

In [61]:
ar=np.ones([3,4],dtype=int)
ar

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [62]:
ar.dtype

dtype('int64')

In [64]:
ar=np.zeros([2,4],dtype='int16')
ar

array([[0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int16)

In [66]:
ar=np.zeros([2,4],dtype='float16')
ar

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float16)

In [67]:
ar=np.zeros([2,4],dtype='complex64')
ar

array([[0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j]], dtype=complex64)

In [69]:
np.int16(ar)

<ipython-input-69-2509708f1082>:1: ComplexWarning: Casting complex values to real discards the imaginary part
  np.int16(ar)


array([[0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int16)